export enum apiNames {
  login = '/login',
  user = '/api/user',
  logout = '/logout',
  post = 'POST',
  put = 'PUT',
  delete = 'DELETE',
  list_action = 'list',
  store_action = 'store',
  update_action = 'update',
  destroy_action = 'destroy',
  get_all = 'get-all',
  get_active = 'get-active',
  change_status = '/api/generic/change-status',
  dashboard = '/api/dashboard',
  users = '/api/users',
  housing = '/api/housing',
  get_rent_expire = 'get-rent-expire',
  identity_document = '/api/identity-document',
  tenancy = '/api/tenancy',
  housing_room = '/api/housing-room',
  housing_payment = '/api/housing-payment',
  collect_and_payment = 'collect-add-payment',
  just_collect = 'just-collect',
  cancel_collect = 'cancel-collect',
}
